RUS:
  base:
    # Russia includes Crimea in OSM, but this is not widely acknowledged
    - [plus, relation, 60189] # Russia
    - [minus, relation, 3788824] # Crimea
  perspectives:
    RUS:
      - [plus, relation, 3788824] # Crimea
    UKR:
      - [minus, relation, 3788824] # Crimea
  interior-points:
    RUS:
      - [34.25, 45.41] # Crimea

UKR:
  base:
    # Ukraine includes Crimea in OSM
    - [plus, relation, 60199] # Ukraine
  perspectives:
    RUS:
      - [minus, relation, 3788824] # Crimea
      - [minus, relation, 71971] # Luhansk
      - [minus, relation, 71973] # Donetsk
  interior-points:
    base:
      - [34.25, 45.41] # Crimea
      - [39.30, 48.57] # Luhansk
      - [37.801, 48.016] # Donetsk
  exterior-points:
    RUS:
      - [34.25, 45.41] # Crimea
      - [39.30, 48.57] # Luhansk
      - [37.801, 48.016] # Donetsk
