SRB:
  base:
    - [plus, relation, 1741311] # Serbia
    - [minus, relation, 2088990] # Kosovo
    - [minus, relation, 214885] # Croatia (Danube river pockets)
  perspectives:
    SRB:
      - [plus, relation, 2088990] # Kosovo
      - [plus, relation, 1741311] # Serbia (Danube river pockets)
  interior-points:
    base:
      - [20.456, 44.817] # Belgrade
    SRB:
      - [21.164, 42.663] # Pristina
  exterior-points:
    base:
      - [21.164, 42.663] # Pristina
XKK:
  base:
    - [plus, relation, 2088990] # Kosovo
  perspectives:
    SRB:
      - [minus, relation, 2088990] # Kosovo
  interior-points:
    base:
      - [21.164, 42.663] # Pristina

# Code for unclaimed Danube areas
# https://en.wikipedia.org/wiki/ISO_3166-1_alpha-3#User-assigned_code_elements
ZZY:
  base:
    - [plus, relation, 19735506] # Pocket 1
    - [plus, relation, 19735507] # Pocket 2
    # Pocket 3 missing in OSM
    # Pocket 4 missing in OSM
    - [plus, relation, 19735505] # Pocket 5
    - [plus, relation, 19735504] # Pocket 6
