MDA:
  base:
    - [plus, relation, 58974] # Moldova
  interior-points:
    base:
      - [28.832, 47.024] # Chișinău
MCO:
  base:
    - [plus, relation, 1124039] # Monaco
  interior-points:
    base:
      - [7.419, 43.731] # Monaco
MNE:
  base:
    - [plus, relation, 53296] # Montenegro
  interior-points:
    base:
      - [19.262, 42.441] # Podgorica
MKD:
  base:
    - [plus, relation, 53293] # North Macedonia
  interior-points:
    base:
      - [21.431, 41.996] # Skopje
NOR:
  base:
    - [plus, relation, 2978650] # Norway
  interior-points:
    base:
      - [10.738, 59.913] # Oslo
SMR:
  base:
    - [plus, relation, 54624] # San Marino
  interior-points:
    base:
      - [12.446, 43.936] # City of San Marino
CHE:
  base:
    - [plus, relation, 51701] # Switzerland
  interior-points:
    base:
      - [7.452, 46.948] # Bern
TUR:
  base:
    - [plus, relation, 174737] # Turkey
  interior-points:
    base:
      - [32.854, 39.920] # Ankara
GBR:
  base:
    - [plus, relation, 62149] # United Kingdom
    - [plus, relation, 3969434] # British Overseas Territories
  perspectives:
    ARG:
      - [minus, relation, 2185374] # Falkland Islands (Las Malvinas)
  interior-points:
    base:
      - [-0.127, 51.507] # London
      - [-57.857, -51.693] # Stanley
VAT:
  base:
    - [plus, relation, 36989] # Vatican City
  interior-points:
    base:
      - [12.452, 41.903] # Vatican City
