CHN:
  base:
    - [minus, relation, 449220] # Taiwan
  perspectives:
    CHN:
      - [plus, relation, 449220] # Taiwan
  interior-points:
    base:
      - [116.391, 39.906] # Beijing
      - [112.8350, 8.8633] # Cuarteron Reef
      - [112.8883, 9.5467] # Fiery Cross Reef
      - [114.2250, 10.2083] # Gaven Reefs
      - [114.4950, 9.9267] # Hughes Reef
      - [114.2833, 9.7183] # Johnson South Reef
      - [115.5317, 9.9017] # Mischief Reef
      - [114.0833, 10.9233] # Subi Reef
    CHN:
      - [121.563, 25.037] # Taipei
  exterior-points:
    base:
      - [121.563, 25.037] # Taipei
TWN:
  base:
    - [plus, relation, 449220] # Taiwan
  perspectives:
    CHN:
      - [minus, relation, 449220] # Taiwan
  interior-points:
    base:
      - [121.563, 25.037] # Taipei
      - [114.3614, 10.3758] # Itu Aba (Taiping Island)
      - [114.3978, 10.3850] # Ban Than Reef (Zhongzhou)
  exterior-points:
    CHN:
      - [121.563, 25.037] # Taipei
