# Accession: 1958
BEL:
  base:
    - [plus, relation, 52411] # Belgium
    - [minus, relation, 11662943] # Rückschlag, a German exclave
  interior-points:
    base:
      - [4.352, 50.846] # Brussels
      - [4.932650, 51.437910] # Baarle-Hertog, an exclave in Netherlands
  exterior-points:
    base:
      - [6.247462, 50.597583] # Rückschlag, an exclave of Germany
FRA:
  base:
    - [plus, relation, 2202162] # France
    - [minus, relation, 365331] # Subtract piece of Italy on south side of Mont Blanc, a part of Italy base
  perspectives:
    FRA:
      - [plus, relation, 2202162] # Re-add that south side of Mont Blanc
  interior-points:
    base:
      - [2.348, 48.853] # Paris
    FRA:
      - [6.867267, 45.830445] # Mont Blanc southern face
DEU:
  base:
    - [plus, relation, 51477] # Germany
    - [minus, relation, 2323309] # Subtract Ems estuary, a part of Netherlands base
  perspectives:
    DEU:
      - [plus, relation, 51477] # Re-add Ems estuary
  interior-points:
    base:
      - [13.395, 52.517] # Berlin
      - [6.247462, 50.597583] # Rückschlag, an exclave in Belgium
    DEU:
      - [6.93501, 53.37087] # Ems estuary
ITA:
  base:
    - [plus, relation, 365331] # Italy
  interior-points:
    base:
      - [12.482, 41.893] # Rome
    ITA:
      - [6.867267, 45.830445] # Mont Blanc southern face
LUX:
  base:
    - [plus, relation, 2171347] # Luxembourg
    - [minus, relation, 51477] # Subtract German overlap along Our River
  interior-points:
    base:
      - [6.129, 49.611] # Luxembourg
NLD:
  base:
    - [plus, relation, 2323309] # Netherlands
    - [minus, relation, 52411] # Subtract Belgium's exclaves in Baarle
  interior-points:
    base:
      - [4.892, 52.373] # Amsterdam
      - [4.930486, 51.444901] # Baarle-Nassau, near an exclave of Belgium
    NLD:
      - [6.93501, 53.37087] # Ems estuary
