CHL:
  base:
    - [plus, relation, 167454] # Chile
  perspectives:
    ARG:
      - [minus, relation, 286393] # Argentina
  interior-points:
    base:
      - [-70.651, -33.437] # Santiago
      - [-73.28, -49.47] # Patagonian Ice Field
ARG:
  base:
    - [plus, relation, 286393] # Argentina
    - [minus, relation, 167454] # Chile includes Patagonian Ice Field
  perspectives:
    ARG:
      - [plus, relation, 286393] # Argentina
  interior-points:
    base:
      - [-58.388, -34.609] # Buenos Aires
    ARG:
      - [-73.28, -49.47] # Patagonian Ice Field
URY:
  base:
    - [plus, relation, 287072] # Uruguay
  interior-points:
    base:
      - [-56.191, -34.905] # Montevideo
BRA:
  base:
    - [plus, relation, 59470] # Brazil
  interior-points:
    base:
      - [-47.882, -15.793] # Brasília
PRY:
  base:
    - [plus, relation, 287077] # Paraguay
  interior-points:
    base:
      - [-57.634, -25.280] # Asuncion
BOL:
  base:
    - [plus, relation, 252645] # Bolivia
  interior-points:
    base:
      - [-68.133, -16.495] # La Paz
PER:
  base:
    - [plus, relation, 288247] # Peru
  interior-points:
    base:
      - [-77.030, -12.045] # Lima
ECU:
  base:
    - [plus, relation, 108089] # Ecuador
  interior-points:
    base:
      - [-78.512, -0.220] # Quito
COL:
  base:
    - [plus, relation, 120027] # Colombia
  interior-points:
    base:
      - [-74.083, 4.653] # Bogota
VEN:
  base:
    - [plus, relation, 272644] # Venezuela
  perspectives:
    VEN:
      - [plus, relation, 16782944] # Guayana Esequiba
  interior-points:
    base:
      - [-66.914, 10.506] # Caracas
    VEN:
      - [-59.15, 5.27] # Mahdia
GUY:
  base:
    - [plus, relation, 287083] # Guyana
  perspectives:
    VEN:
      - [minus, relation, 16782944] # Guayana Esequiba
    SUR:
      - [minus, relation, 12934144] # Tigri area
  interior-points:
    base:
      - [-58.145, 6.803] # Georgetown
      - [-59.15, 5.27] # Mahdia
      - [-57.15, 2.29] # Tigri area
SUR:
  base:
    - [plus, relation, 287082] # Suriname
  perspectives:
    SUR:
      - [plus, relation, 12934144] # Tigri area
      - [plus, relation, 16104167] # Maroni River headwaters
  interior-points:
    base:
      - [-55.170, 5.824] # Paramaribo
    SUR:
      - [-57.15, 2.29] # Tigri area
      - [-54.23, 2.43] # Maroni River headwaters
FRA:
  perspectives:
    SUR:
      - [minus, relation, 16104167] # Maroni River headwaters
  interior-points:
    base:
      - [-54.23, 2.43] # Maroni River headwaters
