RUS:
  base:
    # Russia includes Crimea in OSM, but this is not widely acknowledged
    - [plus, relation, 60189] # Russia
    - [minus, relation, 72639] # Crimea
    - [minus, relation, 1574364] # Sevastopol
  perspectives:
    RUS:
      - [plus, relation, 72639] # Crimea
      - [plus, relation, 1574364] # Sevastopol
      - [plus, relation, 71971] # Luhansk Oblast
      - [plus, relation, 71973] # Donetsk Oblast
      - [plus, relation, 71022] # Kherson Oblast
      - [plus, relation, 71980] # Zaporizhia Oblast
    UKR:
      - [minus, relation, 72639] # Crimea
      - [minus, relation, 1574364] # Sevastopol
  interior-points:
    RUS:
      # Places claimed by Russia as part of 2022 annexation
      - [33.52, 44.61] # Sevastopol
      - [34.10, 44.95] # Simferopol
      - [39.30, 48.57] # Luhansk
      - [37.80, 48.02] # Donetsk
      - [32.61, 46.64] # Kherson
      - [35.12, 47.85] # Zaporizhia
  exterior-points:
    base:
      # Places internationally recognized to be within Ukraine
      - [33.52, 44.61] # Sevastopol
      - [34.10, 44.95] # Simferopol
      - [39.30, 48.57] # Luhansk
      - [37.80, 48.02] # Donetsk
      - [32.61, 46.64] # Kherson
      - [35.12, 47.85] # Zaporizhia

UKR:
  base:
    # Ukraine includes Crimea in OSM
    - [plus, relation, 60199] # Ukraine
  perspectives:
    RUS:
      - [minus, relation, 72639] # Crimea
      - [minus, relation, 1574364] # Sevastopol
      - [minus, relation, 71971] # Luhansk Oblast
      - [minus, relation, 71973] # Donetsk Oblast
      - [minus, relation, 71022] # Kherson Oblast
      - [minus, relation, 71980] # Zaporizhia Oblast
  interior-points:
    base:
      # Places internationally recognized to be within Ukraine
      - [33.52, 44.61] # Sevastopol
      - [34.10, 44.95] # Simferopol
      - [39.30, 48.57] # Luhansk
      - [37.80, 48.02] # Donetsk
      - [32.61, 46.64] # Kherson
      - [35.12, 47.85] # Zaporizhia
  exterior-points:
    RUS:
      # Places claimed by Russia as part of 2022 annexation
      - [33.52, 44.61] # Sevastopol
      - [34.10, 44.95] # Simferopol
      - [39.30, 48.57] # Luhansk
      - [37.80, 48.02] # Donetsk
      - [32.61, 46.64] # Kherson
      - [35.12, 47.85] # Zaporizhia
