IND:
  perspectives:
    PAK:
    - [minus, relation, "fake-IND-Kashmir"]
  exterior-points:
    PAK:
      - [2.3, 2.7] # fake-PAK-Kashmir
      - [2.7, 2.3] # fake-IND-Kashmir

NPL:
  base:
    - [plus, relation, "fake-NPL"]

ESP:
  base:
    - [plus, relation, "fake-ESP"]
  interior-points:
    base:
      - [-2.5, 5.5] # fake-Pheasant-Island

FRA:
  base:
    - [plus, relation, "fake-FRA"]
  interior-points:
    base:
      - [-2.5, 5.5] # fake-Pheasant-Island
