IND:
  perspectives:
    PAK:
    - [minus, relation, "fake-IND-Kashmir"]
  exterior-points:
    PAK:
      - [2.3, 2.7] # fake-PAK-Kashmir
      - [2.7, 2.3] # fake-IND-Kashmir

NPL:
  base:
    - [plus, relation, "fake-NPL"]

ESP:
  base:
    - [plus, relation, "fake-ESP"]
  interior-points:
    base:
      - [-2.3, 5.5] # fake-Pheasant-Island

FRA:
  base:
    - [plus, relation, "fake-FRA"]
  interior-points:
    base:
      - [-2.7, 5.5] # fake-Pheasant-Island

SRB:
  base:
    - [plus, relation, "fake-SRB"] # Serbia
    - [minus, relation, "fake-XKK"] # Kosovo
  perspectives:
    SRB:
      - [plus, relation, "fake-XKK"] # Kosovo
  interior-points:
    SRB:
      - [1.5, 5.5] # Pristina
  exterior-points:
    base:
      - [1.5, 5.5] # Pristina
XKK:
  base:
    - [plus, relation, "fake-XKK"] # Kosovo
  perspectives:
    SRB:
      - [minus, relation, "fake-XKK"] # Kosovo
  interior-points:
    base:
      - [1.5, 5.5] # Pristina
