CHN:
  perspectives:
    CHN:
    - [plus, relation, "fake-TWN"]
  interior-points:
    CHN:
      - [5.0, 4.0] # Taipei
  exterior-points:
    TWN:
      - [5.5, 4.5] # Taipei
TWN:
  base:
  - [plus, relation, "fake-TWN"]
  interior-points:
    base:
      - [5.0, 4.0] # Taipei
